import type { Metadata } from "next";
import "./globals.css"
import { Space_Grotesk } from "next/font/google"
import Header from "@/app/components/Header"
import Footer from "@/app/components/Footer"

const spaceGrotesk = Space_Grotesk({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} antialiased bg-black`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
